# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  projectName: 'Hades'

steps:
#- task: UseDotNet@2
#  displayName: 'Install .NET Core 3.0 SDK'
#  inputs:
#    packageType: 'sdk'
#    version: '3.0.x'
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c $(buildConfiguration) --no-restore'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $(Build.BuildNumber)'
- task: DotNetCoreCLI@2
  displayName: 'Pack Client'
  inputs:
    command: 'pack'
    arguments: '-c $(buildConfiguration) /p:PackageVersion=1.$(Build.BuildNumber)'
    packagesToPack: '**/$(projectName).Client.csproj'
    nobuild: true
    versioningScheme: 'off'
- task: NuGetCommand@2
  displayName: 'Push Client'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'poc-dot-not-clients'
    versioningScheme: 'off'
    allowPackageConflicts: true